### ISSUE TITLE
extending?

### ISSUE THREAD

**Issue by nuelsoft** [fractalliter/movie_trailer#4]
https://github.com/fractalliter/movie_trailer/blob/2462be5e078a3fd188982b0deeee288e69574cb0/src/dto/movieTrailers.dto.ts#L3

Would it not make better sense to have a property on the MovieTrailersDTO to hold the value of MovieDetail? as opposed to completely extending it.

Just a thought

**Comment by fractalliter** [comment]
It sounds controversial 😁.

I thought about having a single DTO for both but it's against clean coding and SOLID principles.

For example the value of the trailers would be always null if a client wants to just have the movie details object from Viaplay side.

I think if we go for a level of segregation in this matter would be cleaner and SOLID.

**Comment by nuelsoft** [comment]
Very true. 

But I would suggest 
`{
details: MovieDetailDTO
trailers: string[]
}`

**Comment by fractalliter** [comment]
Your suggestion is 100 accurate in terms of utilizing composition.

Composition is a way better approach than inheritance in most cases.

And regarding your second thought, I will think about it also to see if I can get ride of DTO completely.
Thanks for mentioning that.
